financial/urls.py
from django.conf.urls import url, include

from financial import views

app_name = 'financial'

urlpatterns = [
    url(r'^live_currency/', views.live_currency),
    url(r'^currency_converter/', views.currency_converter),
    url(r'^online_wallet/', views.online_wallet, name='online_wallet'),
    url(r'^charged/', views.charged, name='charged'),
    url(r'^changed/', views.changed, name='changed'),
    url(r'^internal_payment/', views.internal_payment, name='internal_payment')
]

gspaid/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from misc import urls as misc_urls
from misc import views as misc_views
from authorization import urls as authorization_urls
from financial import urls as financial_urls
from workflow import urls as workflow_urls
from management import urls as management_urls


urlpatterns = [
    url(r'^/', misc_views.about_us),
    url(r'^admin/', admin.site.urls),
    url(r'^misc/', include(misc_urls)),
    url(r'^authorization/', include(authorization_urls)),
    url(r'^management/', include(management_urls)),
    url(r'^financial/', include(financial_urls)),
    url(r'^workflow/', include(workflow_urls)),
    # url(r'^management/', include(management_urls)),
]

misc/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^about_us/', views.about_us),
    url(r'^rules/', views.rules),
    url(r'^dashboard/', views.dashboard, name='dashboard')
]

workflow/urls.py
from django.conf.urls import url, include

from workflow import views

app_name='workflow'

urlpatterns = [
    url(r'^dashboard/', views.costumer_dashboard, name='dashboard'),
    url(r'^requests/', views.requests, name='requests'),
    url(r'^costumer_requests/', views.costumer_new_request, name='costumer_requests'),
]

workflow/models.py
from django.contrib.auth.models import User
from django.db import models
from solo.models import SingletonModel

from financial.models import Currency


class RequestTypeBase(models.Model):
    name = models.CharField(max_length=128, null=False, blank=False)
    description = models.TextField()
    wage_rule = models.CharField(max_length=128, null=False, blank=False, default='0 0')


class ExchangeRequest(RequestTypeBase, SingletonModel):
    pass


class RequestType(RequestTypeBase):
    currency = models.ForeignKey(Currency)
    amount = models.DecimalField(max_digits=128, decimal_places=64)
    information = models.TextField()


class Request(models.Model):
    user = models.ForeignKey(User)
    request_type = models.ForeignKey(RequestType)

    CREATED = 'created'
    IN_PROGRESS = 'in_progress'
    FAILED = 'failed'
    SUCCEEDED = 'succeeded'
    SUSPICIOUS = 'suspicious'

    STATUS_CHOICES = (
        (CREATED, 'Created'),
        (IN_PROGRESS, 'In progress'),
        (FAILED, 'Failed'),
        (SUCCEEDED, 'Succeeded'),
        (SUSPICIOUS, 'Suspicious'),
    )

    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=CREATED)
    attachment = models.FileField()

    user_description = models.TextField()
    employee_description = models.TextField()

workflow/views.py
from django.shortcuts import render


def costumer_dashboard(request):
    return render(request, "workflow/costumer_dashboard.html")


def employee_dashboard(request):
    return requests(request)


def requests(request):
    return render(request, 'workflow/requests_history.html')


def costumer_new_request(request):
    return render(request, "workflow/new_request.html")

workflow/templates/workflow/costumer_dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Dashboard</title>
        <link rel="stylesheet" href="../../../documents/design/wireframe/styles.css">
    </head>
    <body>
        <table>
            <tr>
                <td width="20%">
                    <table>
                        <tbody>
                        <tr><td><a href="{%  url 'profile' %}">Profile</a></td></tr>
                        <tr><td><a href="{%  url 'financial:internal_payment' %}">Internal Payment</a></td></tr>
                        <tr><td><a href="{% url 'financial:online_wallet' %}">Wallet</a></td></tr>
                        <tr><td><a href="{% url 'workflow:costumer_requests' %}">Requests</a></td></tr>
               		<tr><td><a href="{% url 'workflow:requests' %}">Requests History</a></td></tr>
                        <tr><td><a href="{% url 'workflow:dashboard' %}">Log</a></td></tr>
                        </tbody>
                    </table>
                </td>
                <td width="80%">
                    <h2>Notifications</h2>
                    <table>
                        <thead>
                        <th>Time</th>
                        <th>Description</th>
                        </thead>
                        <tbody>
                        <tr>
                            <td>12:50</td>
                            <td style="color: red;">New features has been added to the website my lord!</td>
                        </tr>

                        </tbody>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

workflow/templates/workflow/new_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../styles.css">
    <title>new request</title>
</head>
<body>
<form method="get" action="new_request.html">
    <label for="title">Title: </label>
    <select id="title" value="TOEFL Exam">
        <option value="TOEFL Exam">TOEFL Exam</option>
        <option value="Pay for visa">Pay for visa</option>
    </select>
    
    <label for="amount">Amount: </label>
    <input type="number" id="amount" readonly="readonly" value="100000000">

    <label for="currency">Currency: </label>
    <input type="text" id="currency" readonly="readonly" value="$">

    <br>
    <label for="extra-info">extra info needed: </label>
    <textarea rows="8" type="text" id="extra-info" readonly="readonly">PostalCode  Father's name</textarea>

    <label for="extra-data">extra data: </label>
    <textarea rows="8" type="text" id="extra-data" ></textarea>

    <label for="files">Zipped files</label>
    <input type="file" id="files">

    <input type="submit" value="Submit">

</form>
</body>
</html>

workflow/templates/workflow/requests_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../../documents/design/wireframe/styles.css">
    <title>Transactions History</title>
</head>
<body>
    <h2>Requests</h2>
    <table>
        <thead>
            <th>Employee</th>
            <th>Title</th>
            <th>Status</th>
            <th>Action</th>
        </thead>
        <thead>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Check New Request</a></td>
            </tr>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Details</a></td>
            </tr>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Details</a></td>
            </tr>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Details</a></td>
            </tr>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Details</a></td>
            </tr>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Details</a></td>
            </tr>
            <tr>
                <td>gspaid</td>
                <td>TOEFL Exam</td>
                <td>Quit Done</td>
                <td><a href="../../../documents/design/wireframe/customer/single_request.html">Details</a></td>
            </tr>
        </thead>
    </table>
</body>
</html>