gspaid/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from misc import urls as misc_urls
from misc import views as misc_views
from authorization import urls as authorization_urls
from financial import urls as financial_urls
from workflow import urls as workflow_urls
from management import urls as management_urls


urlpatterns = [
    url(r'^/', misc_views.about_us),
    url(r'^admin/', admin.site.urls),
    url(r'^misc/', include(misc_urls)),
    url(r'^authorization/', include(authorization_urls)),
    url(r'^management/', include(management_urls)),
    url(r'^financial/', include(financial_urls)),
    url(r'^workflow/', include(workflow_urls)),
    # url(r'^management/', include(management_urls)),
]

management/urls.py
from django.conf.urls import url
from management import views

app_name = 'management'

urlpatterns = [
    url(r'^contact_admin', views.contact_admin, name='contact_admin'),
    url(r'^add_request_type', views.add_request_type, name='add_request_type'),
    url(r'^settings_changed', views.settings_changed, name="settings_changed"),
    url(r'^settings', views.settings, name='settings'),
    url(r'^management_dashboard', views.management_dashboard, name='management_dashboard')
]

misc/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^about_us/', views.about_us),
    url(r'^rules/', views.rules),
    url(r'^dashboard/', views.dashboard, name='dashboard')
]

management/models.py
from __future__ import unicode_literals

from django.db import models

from financial.models import Currency


class Ticket(models.Model):
    name = models.CharField(max_length=128, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    message = models.TextField(null=False, blank=False)

management/forms.py
from django.forms import ModelForm

from management.models import Ticket


class ContactAdminForm(ModelForm):
    class Meta:
        model = Ticket
        exclude = []

management/views.py
from django.shortcuts import render
from django.contrib import messages

from management.forms import ContactAdminForm


def contact_admin(request):
    if request.method == 'POST':
        form = ContactAdminForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Sent message to admin.")
    else:
        form = ContactAdminForm()

    return render(
        request,
        template_name='management/contact_admin.html',
        context={
            'form': form
        }
    )


def management_dashboard(request):
    return render(request, "management/management_dashboard.html")


def add_request_type(request):
    return render(request, 'management/new_request_type.html')


def settings(request):
    return render(request, 'management/settings.html')


def settings_changed(request):
    return render(request, 'management/settings_changed.html')

management/templates/management/contact_admin.html
{% extends 'misc/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock content %}

management/templates/management/management_dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Dashboard</title>
        <link rel="stylesheet" href="../../../documents/design/wireframe/styles.css">
    </head>
    <body>
        <table>
            <tr>
                <td width="20%">
                    <table>
                        <tbody>
                        <tr><td><a href="../../../documents/design/wireframe/admin/costumers.html">Users</a></td></tr>
                        <tr><td><a href="../../../documents/design/wireframe/admin/costumers.html">Customers</a></td></tr>
                        <tr><td><a href="../../../documents/design/wireframe/admin/employees.html">Employees</a></td></tr>
                        <tr><td><a href="../../../documents/design/wireframe/admin/requests.html">Requests</a></td></tr>
                        <tr><td><a href="../../../documents/design/wireframe/admin/charge.html">Charge</a></td></tr>
                        <tr><td><a href="{% url 'management:management_dashboard' %}">Log (Dashboard)</a></td></tr>
                        <tr><td><a href="../../../documents/design/wireframe/admin/transactions.html">Currency Report</a></td></tr>
                        <tr><td><a href="{% url 'management:add_request_type' %}">Create New Request Type</a></td></tr>
                        <tr><td><a href="{% url 'management:settings' %}">Settings</a></td></tr>
                        </tbody>
                    </table>
                </td>
                <td width="80%">
                    <h2>Notifications</h2>
                    <table>
                        <thead>
                        <th>Time</th>
                        <th>Description</th>
                        </thead>
                        <tbody>
                        <tr>
                            <td>12:50</td>
                            <td style="color: red;">Not enough money to pay the salary my lord!</td>
                        </tr>
                        <tr>
                            <td>12:50</td>
                            <td>Great things are happening in your company my lord!</td>
                        </tr>
                        <tr>
                            <td>12:50</td>
                            <td>Great things are happening in your company my lord!</td>
                        </tr>
                        <tr>
                            <td>12:50</td>
                            <td>Great things are happening in your company my lord!</td>
                        </tr>
                        <tr>
                            <td>12:50</td>
                            <td>Great things are happening in your company my lord!</td>
                        </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>
                                    <h3>Filter By:</h3>
                                </td>
                                <td>
                                    <form>
                                        <label for="username">User</label>
                                        <select name="username" id="username">
                                            <option value="alto">alto</option>
                                            <option value="gspaid">gspaid</option>
                                        </select>
                                    </form>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

management/templates/management/new_request_type.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../../documents/design/wireframe/styles.css">
    <title>new request type</title>
</head>
<body>
<form method="post" action="">
    <label for="title">Title: </label>
    <input type="text" id="title" value="TOEFEL EXAM">
    
    <label for="amount">Amount: </label>
    <input type="number" id="amount" value="100000000">

    <label for="currency">Currency</label>
    <select id="currency" value="$">
        <option value="EUR">$</option>
        <option value="IRR">Rial</option>
    </select>

    <br>
    <label for="extra-info">extra info needed: </label>
    <textarea rows="8" type="text" id="extra-info" >PostalCode  Father's name</textarea>

    <input type="submit" value="Submit">

</form>
</body>
</html>

management/templates/management/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Settings</title>
</head>
<body>
<form method="get" action="{% url 'management:settings_changed' %}">
    <label for="max_transaction_per_day">Max Transaction Per Day</label>
    <input type="number" id="max_transaction_per_day">
    <label for="min_transaction_per_day">Min Transaction Per Day</label>
    <input type="number" id="min_transaction_per_day">
    <input type="submit">
</form>
</body>
</html>

management/templates/management/settings_changed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Settings Changed</title>
</head>
<body>
<h2>Settings Changed Successfully!</h2>
    <a href="../../../../management/templates/management/management_dashboard.html">Home</a>
</body>
</html>