financial/urls.py
from django.conf.urls import url, include

from financial import views

app_name = 'financial'

urlpatterns = [
    url(r'^live_currency/', views.live_currency),
    url(r'^currency_converter/', views.currency_converter),
    url(r'^online_wallet/', views.online_wallet, name='online_wallet'),
    url(r'^charged/', views.charged, name='charged'),
    url(r'^changed/', views.changed, name='changed'),
    url(r'^internal_payment/', views.internal_payment, name='internal_payment')
]

gspaid/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from misc import urls as misc_urls
from misc import views as misc_views
from authorization import urls as authorization_urls
from financial import urls as financial_urls
from workflow import urls as workflow_urls
from management import urls as management_urls


urlpatterns = [
    url(r'^/', misc_views.about_us),
    url(r'^admin/', admin.site.urls),
    url(r'^misc/', include(misc_urls)),
    url(r'^authorization/', include(authorization_urls)),
    url(r'^management/', include(management_urls)),
    url(r'^financial/', include(financial_urls)),
    url(r'^workflow/', include(workflow_urls)),
    # url(r'^management/', include(management_urls)),
]

misc/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^about_us/', views.about_us),
    url(r'^rules/', views.rules),
    url(r'^dashboard/', views.dashboard, name='dashboard')
]

workflow/urls.py
from django.conf.urls import url, include

from workflow import views

app_name='workflow'

urlpatterns = [
    url(r'^dashboard/', views.costumer_dashboard, name='dashboard'),
    url(r'^requests/', views.requests, name='requests'),
    url(r'^costumer_requests/', views.costumer_new_request, name='costumer_requests'),
]

financial/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
import requests
import json


class Currency(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False, unique=True)

    @property
    def ratio(self):
        conversion_key = 'IRR_' + self.name
        response = requests.request(
            'GET',
            'https://free.currencyconverterapi.com/api/v5/convert?q=%s&compact=ultra' % conversion_key
        )
        return float(json.load(response.text)[conversion_key])


class Transaction(models.Model):
    from_currency = models.ForeignKey(Currency, related_name='going_transaction_set')
    to_currency = models.ForeignKey(Currency, related_name='coming_transaction_set')

    from_amount = models.DecimalField(max_digits=128, decimal_places=64)

    to_amount = models.DecimalField(max_digits=128, decimal_places=64)

    CREATED = 'created'
    FAILED = 'failed'
    SUCCEEDED = 'succeeded'

    STATUS_CHOICES = (
        (CREATED, 'Created'),
        (FAILED, 'Failed'),
        (SUCCEEDED, 'Succeeded'),
    )

    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=CREATED)

    from_user = models.ForeignKey(User, related_name="going_transaction_set")
    to_user = models.ForeignKey(User, related_name="coming_transaction_set")

financial/views.py
from django.shortcuts import render
from misc import views


def live_currency(request):
    return views.about_us(request)


def currency_converter(request):
    return views.about_us(request)


def online_wallet(request):
    return views.render(request, 'financial/online_wallet.html')


def charged(request):
    return views.render(request, 'financial/charged.html')


def changed(request):
    return views.render(request, 'financial/changed.html')


def internal_payment(request):
    return views.render(request, 'financial/internal_payment.html')

financial/templates/financial/changed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Charged</title>
</head>
<body>
<h2>Changed successfully!</h2>
    <a href="{% url 'workflow:dashboard' %}">Home</a>
</body>
</html>

financial/templates/financial/charged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Charged</title>
</head>
<body>
<h2>Account got charged successfully!</h2>
    <a href="{% url 'workflow:dashboard' %}">Home</a>
</body>
</html>

financial/templates/financial/internal_payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../styles.css">
    <title>online wallet</title>
</head>
<body>

<form method="get" action="{% url 'financial:charged' %}">
    <label for="amount">Amount:</label>
    <input type="number" id="amount">
    <label>Rials</label>

<br>
    <label for="account_number">Account Id:</label>
    <input id="account_number">

<br>
    <label for="email">Email:</label>
    <input id="email">
<br>
    <label for="phone">Phone Number:</label>
    <input id="phone">

<br>
    <input type="submit" value="Charge">
</form>

<br>

</body>
</html></title>
</head>
<body>

</body>
</html>

financial/templates/financial/online_wallet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../styles.css">
    <title>online wallet</title>
</head>
<body>
<form method="get" action="online_wallet.html">
    <label for="Rial">Rial: </label>
    <input type="number" id="Rial" readonly="readonly" value="100000000">

    <label for="Doller">Doller: </label>
    <input type="number" id="Doller" readonly="readonly" value="100000000">

    <label for="Euro">Euro: </label>
    <input type="number" id="Euro" readonly="readonly" value="100000000">
</form>

<br>

<form method="get" action="{% url 'financial:charged' %}">
    <label for="amount">Amount to charge:</label>
    <input type="number" id="amount">
    <label>Rials</label>
    <input type="submit" value="Charge">
</form>

<br>

<form method="get" action="{% url 'financial:changed' %}">
    <label for="amount-to-change">Amount to change:</label>
    <input type="number" id="amount-to-change">
    <select id="from-currency" value="$">
        <option value="$">$</option>
        <option value="Rial">Rial</option>
        <option value="Euro">Euro</option>
    </select>
    <label for="amount-to-get">Amount you get:</label>
    <input type="number" readonly="readonly" id="amount-to-get" value="48000">
    <select id="to-currency" value="$">
        <option value="$">$</option>
        <option value="Rial">Rial</option>
        <option value="Euro">Euro</option>
    </select>
    <input id="update-change-info" type="submit" value="update change info">
    <input id="change" type="submit" value="Change!">
</form>

</body>
</html>